name: PipelineWorkflow

on:
  push:
    branches:
	  - master
  pull_request:
    branches:
	  - master

jobs:
  build:
      name: Azure Pipeline
	    runs-on: ubuntu-latest
		steps:
        - namme : Azure Pipeline Action
		  uses: Azure /pipelines@v1
		    with:
              azure-devops-project-url: https://dev.azure.com/johnwebb1993/AgileProject
			  azure-pipeline-name: 'Devops70895.gitapp'
			  azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}